### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by rockers007** [AngularClass/angular2-webpack-starter#935]
I am getting lots of below error,my node version is 6.5.0
and npm version is 3.10.3

ver\index.d.ts:2205:17
    A rest parameter must be of an array type.
[default] E:\nodejs\angular2-webpack-starter\node_modules\@types\selenium-webdri
ver\index.d.ts:2390:18
    A rest parameter must be of an array type.
[default] E:\nodejs\angular2-webpack-starter\node_modules\@types\selenium-webdri
ver\index.d.ts:3256:53
    Cannot find name 'Error'.
[default] E:\nodejs\angular2-webpack-starter\node_modules\@types\selenium-webdri
ver\index.d.ts:3281:28
    A rest parameter must be of an array type.
[default] E:\nodejs\angular2-webpack-starter\node_modules\@types\selenium-webdri
ver\index.d.ts:3290:34
    Cannot find name 'Array'.
[default] E:\nodejs\angular2-webpack-starter\node_modules\@types\selenium-webdri
ver\index.d.ts:3299:47
    Cannot find name 'Function'.
[default] E:\nodejs\angular2-webpack-starter\node_modules\@types\selenium-webdri
ver\index.d.ts:3318:38
    Cannot find name 'Function'.
[default] E:\nodejs\angular2-webpack-starter\node_modules\@types\selenium-webdri
ver\index.d.ts:3326:50
    Cannot find name 'Function'.
[default] E:\nodejs\angular2-webpack-starter\node_modules\@types\selenium-webdri
ver\index.d.ts:3426:125
    Cannot find name 'Date'.
[default] E:\nodejs\angular2-webpack-starter\node_modules\@types\selenium-webdri
ver\index.d.ts:3964:42
    A rest parameter must be of an array type.
[default] E:\nodejs\angular2-webpack-starter\node_modules\@types\selenium-webdri
ver\index.d.ts:3965:34
    Cannot find name 'Function'.
[default] E:\nodejs\angular2-webpack-starter\node_modules\@types\selenium-webdri
ver\index.d.ts:3965:44
    A rest parameter must be of an array type.
[default] E:\nodejs\angular2-webpack-starter\node_modules\@types\selenium-webdri
ver\index.d.ts:4043:46
    Cannot find name 'Function'.
[default] E:\nodejs\angular2-webpack-starter\node_modules\@types\selenium-webdri
ver\index.d.ts:4043:56
    A rest parameter must be of an array type.
[default] E:\nodejs\angular2-webpack-starter\node_modules\@types\selenium-webdri
ver\index.d.ts:4055:22
    A rest parameter must be of an array type.
[default] E:\nodejs\angular2-webpack-starter\node_modules\@types\selenium-webdri
ver\index.d.ts:4055:94
    A rest parameter must be of an array type.
[default] E:\nodejs\angular2-webpack-starter\node_modules\@types\selenium-webdri
ver\index.d.ts:4213:66
    Cannot find name 'Function'.
[default] E:\nodejs\angular2-webpack-starter\node_modules\@types\selenium-webdri
ver\index.d.ts:4228:71
    Cannot find name 'Function'.
[default] E:\nodejs\angular2-webpack-starter\node_modules\@types\selenium-webdri
ver\index.d.ts:4238:47
    Cannot find name 'Function'.
[default] E:\nodejs\angular2-webpack-starter\node_modules\@types\selenium-webdri
ver\index.d.ts:4373:18
    A rest parameter must be of an array type.
[default] E:\nodejs\angular2-webpack-starter\node_modules\@types\selenium-webdri
ver\index.d.ts:4557:46
    Cannot find name 'Function'.
[default] E:\nodejs\angular2-webpack-starter\node_modules\@types\selenium-webdri
ver\index.d.ts:4568:51
    Cannot find name 'Function'.
[default] E:\nodejs\angular2-webpack-starter\node_modules\@types\selenium-webdri
ver\index.d.ts:4579:47
    Cannot find name 'Function'.
[default] E:\nodejs\angular2-webpack-starter\node_modules\@types\selenium-webdri
ver\index.d.ts:4697:46
    Cannot find name 'Function'.
[default] E:\nodejs\angular2-webpack-starter\node_modules\@types\selenium-webdri
ver\index.d.ts:4708:51
    Cannot find name 'Function'.
[default] E:\nodejs\angular2-webpack-starter\node_modules\@types\selenium-webdri
ver\index.d.ts:4719:47
    Cannot find name 'Function'.
[default] E:\nodejs\angular2-webpack-starter\node_modules\@types\selenium-webdri
ver\index.d.ts:4781:18
    A rest parameter must be of an array type.
[default] E:\nodejs\angular2-webpack-starter\node_modules\@types\selenium-webdri
ver\index.d.ts:4781:31
    Cannot find name 'Array'.
[default] E:\nodejs\angular2-webpack-starter\node_modules\@types\selenium-webdri
ver\index.d.ts:5131:34
    A rest parameter must be of an array type.
[default] E:\nodejs\angular2-webpack-starter\node_modules\@types\selenium-webdri
ver\index.d.ts:5247:52
    Cannot find name 'Function'.
[default] E:\nodejs\angular2-webpack-starter\node_modules\@types\selenium-webdri
ver\index.d.ts:5319:41
    Cannot find name 'Function'.
[default] E:\nodejs\angular2-webpack-starter\node_modules\@types\selenium-webdri
ver\index.d.ts:5326:42
    Cannot find name 'Function'.
[default] E:\nodejs\angular2-webpack-starter\node_modules\@types\selenium-webdri
ver\index.d.ts:5332:24
    Cannot find name 'Function'.
[default] E:\nodejs\angular2-webpack-starter\node_modules\@types\selenium-webdri
ver\index.d.ts:5338:28
    Cannot find name 'Function'.
[default] E:\nodejs\angular2-webpack-starter\node_modules\@types\selenium-webdri
ver\index.d.ts:5344:25
    Cannot find name 'Function'.
[default] E:\nodejs\angular2-webpack-starter\node_modules\@types\selenium-webdri
ver\index.d.ts:5350:29
    Cannot find name 'Function'.
[default] E:\nodejs\angular2-webpack-starter\node_modules\@types\selenium-webdri
ver\index.d.ts:5357:35
    Cannot find name 'Function'.
[default] E:\nodejs\angular2-webpack-starter\node_modules\@types\selenium-webdri
ver\index.d.ts:5365:36
    Cannot find name 'Function'.
[default] E:\nodejs\angular2-webpack-starter\node_modules\@types\selenium-webdri
ver\index.d.ts:5372:36
    Cannot find name 'Function'.
[default] E:\nodejs\angular2-webpack-starter\node_modules\@types\source-map\inde
x.d.ts:17:18
    Cannot find name 'Array'.
[default] E:\nodejs\angular2-webpack-starter\node_modules\@types\source-map\inde
x.d.ts:18:16
    Cannot find name 'Array'.
[default] E:\nodejs\angular2-webpack-starter\node_modules\@types\uglify-js\index
.d.ts:92:18
    Cannot find name 'Object'.
[default] E:\nodejs\angular2-webpack-starter\node_modules\@types\uglify-js\index
.d.ts:94:20
    Cannot find name 'Object'.
[default] E:\nodejs\angular2-webpack-starter\node_modules\@types\uglify-js\index
.d.ts:102:37
    Cannot find name 'Array'.
[default] E:\nodejs\angular2-webpack-starter\node_modules\@types\uglify-js\index
.d.ts:258:40
    Cannot find name 'Function'.
[default] E:\nodejs\angular2-webpack-starter\node_modules\@types\uglify-js\index
.d.ts:263:26
    Cannot find name 'Function'.
[default] E:\nodejs\angular2-webpack-starter\node_modules\@types\uglify-js\index
.d.ts:266:27
    Cannot find name 'Function'.
[default] E:\nodejs\angular2-webpack-starter\node_modules\@types\uglify-js\index
.d.ts:269:27
    Cannot find name 'Function'.
[default] E:\nodejs\angular2-webpack-starter\node_modules\@types\uglify-js\index
.d.ts:323:16
    Cannot find name 'Object'.
[default] E:\nodejs\angular2-webpack-starter\node_modules\@types\uglify-js\index
.d.ts:323:25
    Cannot find name 'JSON'.
[default] E:\nodejs\angular2-webpack-starter\node_modules\@types\uglify-js\index
.d.ts:396:23
    Cannot find name 'Object'.
[default] E:\nodejs\angular2-webpack-starter\node_modules\@types\uglify-js\index
.d.ts:409:46
    Cannot find name 'Function'.
[default] E:\nodejs\angular2-webpack-starter\node_modules\@types\webpack\index.d
.ts:64:29
    Cannot find name 'Function'.
[default] E:\nodejs\angular2-webpack-starter\node_modules\@types\webpack\index.d
.ts:133:19
    Cannot find name 'RegExp'.
[default] E:\nodejs\angular2-webpack-starter\node_modules\@types\webpack\index.d
.ts:133:28
    Cannot find name 'RegExp'.
[default] E:\nodejs\angular2-webpack-starter\node_modules\@types\webpack\index.d
.ts:136:32
    Cannot find name 'RegExp'.
[default] E:\nodejs\angular2-webpack-starter\node_modules\@types\webpack\index.d
.ts:139:29
    Cannot find name 'RegExp'.
[default] E:\nodejs\angular2-webpack-starter\node_modules\@types\webpack\index.d
.ts:142:32
    Cannot find name 'RegExp'.
[default] E:\nodejs\angular2-webpack-starter\node_modules\@types\webpack\index.d
.ts:180:23
    Cannot find name 'RegExp'.
[default] E:\nodejs\angular2-webpack-starter\node_modules\@types\webpack\index.d
.ts:180:32
    Cannot find name 'RegExp'.
[default] E:\nodejs\angular2-webpack-starter\node_modules\@types\webpack\index.d
.ts:188:38
    Cannot find name 'RegExp'.
[default] E:\nodejs\angular2-webpack-starter\node_modules\@types\webpack\index.d
.ts:215:37
    Cannot find name 'RegExp'.
[default] E:\nodejs\angular2-webpack-starter\node_modules\@types\webpack\index.d
.ts:418:21
    Cannot find name 'RegExp'.
[default] E:\nodejs\angular2-webpack-starter\node_modules\@types\webpack\index.d
.ts:531:39
    Cannot find name 'Error'.
[default] E:\nodejs\angular2-webpack-starter\node_modules\rxjs\Observable.d.ts:1
0:66
    Cannot find name 'Promise'.
[default] E:\nodejs\angular2-webpack-starter\node_modules\rxjs\Observable.d.ts:1
1:69
    Cannot find name 'ArrayLike'.
[default] E:\nodejs\angular2-webpack-starter\node_modules\rxjs\Observable.d.ts:3
8:20
    Cannot find name 'Function'.
[default] E:\nodejs\angular2-webpack-starter\node_modules\rxjs\Observable.d.ts:6
6:60
    Cannot find name 'Promise'.
[default] E:\nodejs\angular2-webpack-starter\node_modules\rxjs\Observable.d.ts:6
6:70
    Cannot find name 'Promise'.
[default] E:\nodejs\angular2-webpack-starter\node_modules\rxjs\Subject.d.ts:12:2
0
    Cannot find name 'Function'.
[default] E:\nodejs\angular2-webpack-starter\node_modules\rxjs\Subscription.d.ts
:4:61
    Cannot find name 'Function'.
[default] E:\nodejs\angular2-webpack-starter\node_modules\rxjs\observable\ArrayO
bservable.d.ts:20:18
    A rest parameter must be of an array type.
[default] E:\nodejs\angular2-webpack-starter\node_modules\rxjs\observable\ArrayO
bservable.d.ts:20:28
    Cannot find name 'Array'.
[default] E:\nodejs\angular2-webpack-starter\node_modules\typescript\lib\lib.es2
015.d.ts:17:1
    File 'E:/nodejs/angular2-webpack-starter/node_modules/typescript/lib/lib.es2
015.core.d.ts' not found.
[default] E:\nodejs\angular2-webpack-starter\node_modules\typescript\lib\lib.es2
015.d.ts:18:1
    File 'E:/nodejs/angular2-webpack-starter/node_modules/typescript/lib/lib.es2
015.collection.d.ts' not found.
[default] E:\nodejs\angular2-webpack-starter\node_modules\typescript\lib\lib.es2
015.d.ts:19:1
    File 'E:/nodejs/angular2-webpack-starter/node_modules/typescript/lib/lib.es2
015.generator.d.ts' not found.
[default] E:\nodejs\angular2-webpack-starter\node_modules\typescript\lib\lib.es2
015.d.ts:20:1
    File 'E:/nodejs/angular2-webpack-starter/node_modules/typescript/lib/lib.es2
015.iterable.d.ts' not found.
[default] E:\nodejs\angular2-webpack-starter\node_modules\typescript\lib\lib.es2
015.d.ts:21:1
    File 'E:/nodejs/angular2-webpack-starter/node_modules/typescript/lib/lib.es2
015.promise.d.ts' not found.
[default] E:\nodejs\angular2-webpack-starter\node_modules\typescript\lib\lib.es2
015.d.ts:22:1
    File 'E:/nodejs/angular2-webpack-starter/node_modules/typescript/lib/lib.es2
015.proxy.d.ts' not found.
[default] E:\nodejs\angular2-webpack-starter\node_modules\typescript\lib\lib.es2
015.d.ts:23:1
    File 'E:/nodejs/angular2-webpack-starter/node_modules/typescript/lib/lib.es2
015.reflect.d.ts' not found.
[default] E:\nodejs\angular2-webpack-starter\node_modules\typescript\lib\lib.es2
015.d.ts:24:1
    File 'E:/nodejs/angular2-webpack-starter/node_modules/typescript/lib/lib.es2
015.symbol.d.ts' not found.
[default] E:\nodejs\angular2-webpack-starter\node_modules\typescript\lib\lib.es2
015.d.ts:25:1
    File 'E:/nodejs/angular2-webpack-starter/node_modules/typescript/lib/lib.es2
015.symbol.wellknown.d.ts' not found.
[default] E:\nodejs\angular2-webpack-starter\node_modules\typescript\lib\lib.es2
015.d.ts:26:1
    File 'E:/nodejs/angular2-webpack-starter/node_modules/typescript/lib/lib.es5
.d.ts' not found.
[default] E:\nodejs\angular2-webpack-starter\src\app\app.module.ts:23:6
    Type '{}' is not an array type.
[default] E:\nodejs\angular2-webpack-starter\src\app\app.module.ts:59:48
    Property 'map' does not exist on type '{}'.
[default] E:\nodejs\angular2-webpack-starter\src\app\app.service.ts:17:15
    Cannot find name 'Error'.
[default] E:\nodejs\angular2-webpack-starter\src\app\app.service.ts:35:12
    Cannot find name 'JSON'.
[default] E:\nodejs\angular2-webpack-starter\src\app\app.service.ts:35:23
    Cannot find name 'JSON'.
[default] E:\nodejs\angular2-webpack-starter\src\app\environment.ts:21:8
    Type '{}' is not an array type.
[default] E:\nodejs\angular2-webpack-starter\src\app\environment.ts:40:8
    Type '{}' is not an array type.
[default] E:\nodejs\angular2-webpack-starter\src\app\environment.ts:49:6
    Type '{}' is not an array type.
[default] E:\nodejs\angular2-webpack-starter\src\custom-typings.d.ts:55:30
    Cannot find name 'Promise'.
[default] E:\nodejs\angular2-webpack-starter\src\custom-typings.d.ts:66:42
    Cannot find name 'Promise'.
[default] E:\nodejs\angular2-webpack-starter\src\custom-typings.d.ts:70:29
    Cannot find name 'Promise'.
[default] E:\nodejs\angular2-webpack-starter\src\custom-typings.d.ts:74:32
    Cannot find name 'Function'.
[default] E:\nodejs\angular2-webpack-starter\src\custom-typings.d.ts:81:30
    Cannot find name 'Function'.
[default] E:\nodejs\angular2-webpack-starter\src\custom-typings.d.ts:94:46
    Cannot find name 'Error'.
[default] E:\nodejs\angular2-webpack-starter\src\custom-typings.d.ts:95:44
    Cannot find name 'Error'.
[default] E:\nodejs\angular2-webpack-starter\src\custom-typings.d.ts:104:34
    A rest parameter must be of an array type.
[default] E:\nodejs\angular2-webpack-starter\src\custom-typings.d.ts:106:70
    Cannot find name 'RegExp'.
[default] E:\nodejs\angular2-webpack-starter\src\main.browser.ts:17:25
    Cannot find name 'Promise'.
[default] E:\nodejs\angular2-webpack-starter\src\polyfills.browser.ts:43:3
    Cannot find name 'Error'.
[default] E:\nodejs\angular2-webpack-starter\src\polyfills.browser.ts:43:27
    Cannot find name 'Infinity'.
[default] Checking finished with 891 errors

**Comment by katallaxie** [comment]
It seems the Typescript Beta was ahead. 8c20ade6294b5721eb8514880d526aafae87e2e1 should fix this. Please, try with Node 4.5.0 (LTS).

**Comment by rockers007** [comment]
Now facing these error


ERROR in ./src/polyfills.browser.ts
Module build failed: TypeError: this.ts.getAutomaticTypeDirectiveNames is not a
function
    at State.loadTypesFromConfig (E:\nodejs\angular2-webpack-starter\node_module
s\awesome-typescript-loader\src\host.ts:148:36)
    at new State (E:\nodejs\angular2-webpack-starter\node_modules\awesome-typesc
ript-loader\src\host.ts:142:14)
    at Object.ensureInstance (E:\nodejs\angular2-webpack-starter\node_modules\aw
esome-typescript-loader\src\instance.ts:150:19)
    at compiler (E:\nodejs\angular2-webpack-starter\node_modules\awesome-typescr
ipt-loader\src\index.ts:37:20)
    at Object.loader (E:\nodejs\angular2-webpack-starter\node_modules\awesome-ty
pescript-loader\src\index.ts:18:18)

ERROR in ./src/vendor.browser.ts
Module build failed: TypeError: this.ts.getAutomaticTypeDirectiveNames is not a
function
    at State.loadTypesFromConfig (E:\nodejs\angular2-webpack-starter\node_module
s\awesome-typescript-loader\src\host.ts:148:36)
    at new State (E:\nodejs\angular2-webpack-starter\node_modules\awesome-typesc
ript-loader\src\host.ts:142:14)
    at Object.ensureInstance (E:\nodejs\angular2-webpack-starter\node_modules\aw
esome-typescript-loader\src\instance.ts:150:19)
    at compiler (E:\nodejs\angular2-webpack-starter\node_modules\awesome-typescr
ipt-loader\src\index.ts:37:20)
    at Object.loader (E:\nodejs\angular2-webpack-starter\node_modules\awesome-ty
pescript-loader\src\index.ts:18:18)

ERROR in ./src/main.browser.ts
Module build failed: TypeError: this.ts.getAutomaticTypeDirectiveNames is not a
function
    at State.loadTypesFromConfig (E:\nodejs\angular2-webpack-starter\node_module
s\awesome-typescript-loader\src\host.ts:148:36)
    at new State (E:\nodejs\angular2-webpack-starter\node_modules\awesome-typesc
ript-loader\src\host.ts:142:14)
    at Object.ensureInstance (E:\nodejs\angular2-webpack-starter\node_modules\aw
esome-typescript-loader\src\instance.ts:150:19)
    at compiler (E:\nodejs\angular2-webpack-starter\node_modules\awesome-typescr
ipt-loader\src\index.ts:37:20)
    at Object.loader (E:\nodejs\angular2-webpack-starter\node_modules\awesome-ty
pescript-loader\src\index.ts:18:18)
Child html-webpack-plugin for "index.html":
        + 3 hidden modules

**Comment by abdulhaq-e** [comment]
@rockers007 Make sure to to have the latest `package.json` rather than the one in #8c20ade . Typescript version has to be exactly `2.0.0`

**Comment by jshamley** [comment]
Not fixed for me with both https://github.com/AngularClass/angular2-webpack-starter/commit/59b4e042a8d1e867c71ae46db978ce1d84864989 and the `package.json` updates in https://github.com/AngularClass/angular2-webpack-starter/commit/8c20ade6294b5721eb8514880d526aafae87e2e1 - I still get 413 errors

**Comment by jshamley** [comment]
This has been fixed, try pulling the latest code.

**Comment by katallaxie** [comment]
https://github.com/AngularClass/angular2-webpack-starter/issues/934#issuecomment-243834589
